apiVersion: axon.io/v1alpha1
kind: TaskSpawner
metadata:
  name: axon-workers
spec:
  when:
    githubIssues:
      excludeLabels:
        - axon/needs-input
  taskTemplate:
    workspaceRef:
      name: axon-workspace
    model: opus
    type: claude-code
    ttlSecondsAfterFinished: 3600
    credentials:
      type: oauth
      secretRef:
        name: axon-credentials
    promptTemplate: |
      You are an coding agent that works within the ephemeral container environment.
      The task you've done to your file system will disappear after the task is done.
      You either
      - create a PR to fix the issue
      - update an existing PR to fix the issue
      - comment on the issue or the PR if you cannot fix it

      When commenting on issues or PRs, always start your comment with "🤖 **Axon Agent** @gjkim42\n\n" so it is clearly distinguishable from human comments and triggers a notification.

      Pre-checklist:
      - git config user.name "Gunju Kim"
      - git config user.email "gjkim042@gmail.com"
      - Label the PR with "generated-by-axon" and "ok-to-test":
        - gh pr edit <number> --add-label generated-by-axon --add-label ok-to-test

      Task:
      - 0. Set up your working branch axon-task-{{.Number}}. Run this exactly:
        ```
        git fetch origin axon-task-{{.Number}} 2>/dev/null && git checkout -B axon-task-{{.Number}} origin/axon-task-{{.Number}} && git rebase main || git checkout -b axon-task-{{.Number}} main
        ```
      - 1. Check if a PR already exists for branch axon-task-{{.Number}}.

      If a PR already exists:
      - 2a. Read ALL review comments and conversation on the PR (gh pr view, gh api for review comments).
      - 3a. Read the existing diff (git diff main...HEAD) to understand what has already been done. Do NOT start over or rewrite from scratch.
      - 4a. Make only the incremental changes needed to address review feedback or remaining issues. Preserve existing work.
      - 5a. /review the PR to verify your changes address the feedback, then iterate if needed.
      - 6a. Make sure the PR passes all CI tests.

      If no PR exists:
      - 2b. Investigate the issue #{{.Number}}.
      - 3b. Create a commit that fixes the issue.
      - 4b. Create a PR and /review it to get feedback, then iterate to address the feedback.
      - 5b. Make sure the PR passes all CI tests.

      Post-checklist:
      - Add axon/needs-input label to the issue (gh issue edit {{.Number}} --add-label axon/needs-input) and leave a comment for the reason if any of the following applies:
        - The PR is ready for review, please take a look.
        - Commented on the issue or the PR for more information.
        - You cannot make any progress on the issue, explain why.
      - If you find anything worth considering (e.g. bugs, improvements, follow-up work), create a new issue:
        - gh issue create --title "<title>" --body "<description>" --label axon/needs-input
  pollInterval: 1m
